# Setup
title:        GW Computer Science Club
tagline:      We Learn &emsp; We Create &emsp; We Share
baseurl:      ""
locale:       "ch"
email:        "286988023@qq.com"

# About/contact
author:
  name:       GZFLS Computer Science Club
  url:        http://yourhomepage.com 

url: "https://gwcs.xyz" # the base hostname & protocol for your site

#Others
plugins:
  - jekyll-sitemap
  - jekyll-loading-lazy

sass:
    style: compressed

markdown: kramdown
name: GZFLS Computer Science
description: Computer Science club @ GZFLS，提供算法竞赛培训，机器人竞赛等，我们也会不定期更新论文精读和有趣的 Arduino Project
