# Setup
title:        GW Computer Science Club
tagline:      We Learn &emsp; We Create &emsp; We Share
baseurl:      ""
paginate:     1
locale:       "ch"
email:        "286988023@qq.com"

# About/contact
author:
  name:       GZFLS Computer Science Club
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others

sass:
    style: compressed

markdown: kramdown
