# Setup
title:        GW Computer Science Club
tagline:      We Learn &emsp; We Create &emsp; We Share
baseurl:      ""
locale:       "ch"
email:        "286988023@qq.com"

# About/contact
author:
  name:       GZFLS Computer Science Club
  url:        http://yourhomepage.com 

url: "https://gwcs.xyz" # the base hostname & protocol for your site

#Others
plugins:
  - jekyll-sitemap
  - jekyll-loading-lazy

sass:
    style: compressed

markdown: kramdown
