# Setup
title:        CHGZFLS Computer Science Club
tagline:      We Learn, We Create, We Share
baseurl:      "/chgzfls-cs-club"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       GZFLS Computer Science Club
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown