# Setup
title:        GW Computer Science Club
tagline:      We Learn &emsp; We Create &emsp; We Share
baseurl:      ""
paginate:     1
locale:       "ch"
google_analytics: G-PG2BP9ZVD5

# About/contact
author:
  name:       GZFLS Computer Science Club
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

usaco-post:
  -
    scope:
      path: ""
      values:
        comments: true